name: Playwright Java Tests with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Change to the version you need
          distribution: 'temurin'

      - name: Install Playwright dependencies
        run: |
          ./gradlew playwrightInstallDeps

      # Grant execute permission for the Gradle wrapper script
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # Install dependencies and build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Run the Playwright Java tests
      - name: Run tests
        run: ./gradlew playwrightTest

    # Upload test results
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test

      # Upload logs and screenshots on failure
      - name: Upload logs and screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: |
            /playwright_test_log.txt
            build/allure-results/screenshots
